#!/bin/bash

entorno="$HOME/Escritorio/venv"
directorio="$entorno/instituto"
repo="https://gitlab.com/Naueru2/Instituto210.git"
echo "creando entorno virtual"
if [ ! -d "$entorno" ]
then
    python3 -m venv "$entorno"
    echo "Entorno virtual creado"
else
    echo "Ya existe, señor"
fi

source "$entorno/bin/activate"
echo "clonando repositorio"
sleep 0.5
if [ ! -d "$directorio" ]
then
    git clone "$repo" "$directorio"
    echo "Repositorio clonado con exito"
else
    echo "El directorio ya existe"
fi
echo "se activo el entorno virtual"
sleep 0.5
source /$HOME/Escritorio/venv/bin/activate
echo "instalando dependencias"
sleep 0.5
pip install django
cd "$HOME/Escritorio/venv/instituto/gestionInstituto"
mv settingsodl.py settings.py
cd "$HOME/Escritorio/venv/instituto/"
pip install pillow
git checkout front
python3 manage.py migrate
python3 manage.py migrate --run-syncdb
python3 manage.py createsuperuser
python3 manage.py runserver

echo "termino el proceso"
